"""permission table modified

Revision ID: 474c7914c760
Revises: 4f89b095e7c8
Create Date: 2024-04-09 10:32:21.167003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '474c7914c760'
down_revision = '4f89b095e7c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_create', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_read', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_delete', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('can_modify', sa.Boolean(), nullable=False))
        batch_op.drop_column('system_name')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('system_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('can_modify')
        batch_op.drop_column('can_delete')
        batch_op.drop_column('can_read')
        batch_op.drop_column('can_create')

    # ### end Alembic commands ###
