"""post, comment, and thread tables made voteable

Revision ID: 4f89b095e7c8
Revises: e5ad3b3ae180
Create Date: 2024-04-08 10:31:59.240594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f89b095e7c8'
down_revision = 'e5ad3b3ae180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voteable', sa.Boolean(), nullable=False))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voteable', sa.Boolean(), nullable=False))

    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voteable', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('voteable')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('voteable')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('voteable')

    # ### end Alembic commands ###
