"""relation between user, view and post established

Revision ID: a1d8fa8d571e
Revises: 6cf008d49ac3
Create Date: 2024-04-05 11:02:10.018438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1d8fa8d571e'
down_revision = '6cf008d49ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('viewed_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('viewed_at')

    # ### end Alembic commands ###
