"""permissions table created

Revision ID: ea9529724ff4
Revises: 1bc20df72ba8
Create Date: 2024-04-04 17:02:53.028275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9529724ff4'
down_revision = '1bc20df72ba8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'content_types', ['content_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permissions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('content_type_id')

    # ### end Alembic commands ###
