"""relation between user and post created

Revision ID: fb257b1a9741
Revises: ca7e9c860f86
Create Date: 2024-04-05 12:09:35.555560

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fb257b1a9741"
down_revision = "ca7e9c860f86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
